# Generated by Django 5.2.17 on 2026-09-10 15:48

import django.db.models.deletion
from django.db import migrations, models

import pulpcore.plugin.util


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0148_artifact_artifact_domain_size_index"),
        ("maven", "0012_add_rbac_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MavenIndexPage",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "_pulp_domain",
                    models.ForeignKey(
                        default=pulpcore.plugin.util.get_domain_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.domain",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("path", "sha256", "_pulp_domain")},
            },
            bases=("core.content",),
        ),
    ]
